version : 0.2

phases:
  install:
    commands:
      - apt-get install -y unzip
  build:
    commands:
      - echo Build started on date
      - zip website.zip ./index.html

artifacts:
  type:
  files:
    - index.html
    - appspec.yml
    - scripts/install_dependencies
    - scripts/start_server
    - images/1.jpg
    - images/2.jpg